language: node_js
node_js:
  - "4.2"

sudo: false

env:
  - DIR=api

before_install:
  - cd $DIR
  - cp config/config_travis-ci.js config/config.js

install:
  - npm install -g mocha
  - npm install

before_script:
  - cd ..

script:
  - make test

services:
  - mongodb
  - redis-server

notifications:
  email: false