language: node_js
node_js:
  - "4.0.0"

sudo: false

before_install:
  - cp config/config_travis-ci.js config/config.js

install:
  - npm install

services:
  - mongodb
  - redis-server

notifications:
  email: false
  slack:
    rooms:
      - 'khe:tfhhTbfsGC5sNlqxUbmU9OZF#development'
    on_success: change
    on_failure: change